name: "Setup Node.js and pnpm"
description: "Setup Node.js and pnpm with caching"
inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "22.18.0"
  pnpm-version:
    description: "pnpm version to use"
    required: false
    default: "10.14.0"

runs:
  using: "composite"
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
