name: Node.js Build

on:
  push:
  pull_request:

env:
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Read Node version from .nvmrc
      - name: Read Node version from .nvmrc
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      # Setup Node.js with the version from .nvmrc
      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.0.0

      - run: pnpm install --frozen-lockfile

      # - run: pnpm run lint # uncomment when eslint is fixed
      - run: pnpm run build