name: Setup Node.js and pnpm

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "22.18.0"
      pnpm-version:
        description: "pnpm version to use"
        required: false
        type: string
        default: "12.8.1"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup PNPM
        uses: pnpm/action-setup@v6.1.0
        with:
          version: ${{ inputs.pnpm-version }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
